.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. litelira_qt test_litelira_qt
clean: FORCE
	$(MAKE) -C .. litelira_qt_clean test_litelira_qt_clean
check: FORCE
	$(MAKE) -C .. test_litelira_qt_check
litelira-qt litelira-qt.exe: FORCE
	 $(MAKE) -C .. litelira_qt
